In [1]:
import numpy as np


In [2]:
array=np.array([1,2,3])
print(array)

[1 2 3]


In [14]:
array2=np.array([1,2,3,4,5,6])
print(array2.shape)

(6,)


In [15]:
#reshape
a=array2.reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [16]:
print("Shape:",a.shape)

Shape: (2, 3)


In [17]:
print("Dimension:",a.ndim)

Dimension: 2


In [18]:
print("Data Type:",a.dtype.name)

Data Type: int32


In [19]:
print("size",a.size)

size 6


In [20]:
print("type:",type(a))


type: <class 'numpy.ndarray'>


In [21]:
array3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [22]:
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
array3.shape

(3, 4)

In [24]:
#zeros
zeros=np.zeros((3,4))

In [25]:
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
zeros[0,0]=4
print(zeros)

[[4. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
ones=np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
np.empty((4,5))

array([[6.23042070e-307, 7.56587584e-307, 1.37961302e-306,
        6.23053614e-307, 6.23053954e-307],
       [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
        9.34603000e-307, 1.78018403e-306],
       [8.90106955e-307, 1.60218491e-306, 1.78018403e-306,
        1.69119330e-306, 6.23054633e-307],
       [1.24610927e-306, 1.05698817e-307, 1.11261638e-306,
        1.33511562e-306, 2.22522596e-306]])

In [29]:
np.arange(10,50,5)


array([10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
#linspace
a=np.linspace(0,10,20)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [33]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [34]:
liste=[1,2,3,4]
array=np.array([5,6,7,8])
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [35]:
a=np.array([1,2,3])

In [36]:
b=a
c=a

In [37]:
b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [38]:
a[0]=5

In [39]:
d=a.copy()
print(d)

[5 2 3]


In [40]:
d

array([5, 2, 3])

In [41]:
a=np.array([1,2,3,4,5,6,7])

In [42]:
a[0]

1

In [43]:
a[0:4]

array([1, 2, 3, 4])

In [44]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [57]:
b=np.array(([1,2,3,4,5],[6,7,8,9,10]))
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
print(b[1,1])
7

7


7

In [59]:
b[1,:]

array([ 6,  7,  8,  9, 10])

In [60]:
b[:,-1]

array([ 5, 10])

In [61]:
b=b.ravel()
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [64]:
b.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])